config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#create
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#               admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                           POST   /admin/users(.:format)                                                                   admin/users#create
#            new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#           edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                           PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                           PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                           DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#                      root GET    /                                                                                        tasks#index
#          confirm_new_task POST   /tasks/new/confirm(.:format)                                                             tasks#confirm_new
#              import_tasks POST   /tasks/import(.:format)                                                                  tasks#import
#                     tasks GET    /tasks(.:format)                                                                         tasks#index
#                           POST   /tasks(.:format)                                                                         tasks#create
#                  new_task GET    /tasks/new(.:format)                                                                     tasks#new
#                 edit_task GET    /tasks/:id/edit(.:format)                                                                tasks#edit
#                      task GET    /tasks/:id(.:format)                                                                     tasks#show
#                           PATCH  /tasks/:id(.:format)                                                                     tasks#update
#                           PUT    /tasks/:id(.:format)                                                                     tasks#update
#                           DELETE /tasks/:id(.:format)                                                                     tasks#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  get  '/login'   , to: 'sessions#new'
  post '/login'   , to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
    post :import, on: :collection
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :bigint           not null, primary key
#  description  :text
#  name         :string(30)       not null
#  status_value :integer          default("notyet"), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_tasks_on_user_id  (user_id)
#

class Task < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validates :status_value, presence: true

  enum status_value: {
    notyet:    0,
    ongoing:   1,
    waiting:   2,
    pending:   3,
    completed: 4,
  }

  def self.csv_attributes
    ["name", "description", "status_value", "created_at", "updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map{ |attr| task.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      task = new
      task.attributes = row.to_hash.slice(*csv_attributes)
      task.save!
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name updated_at status_value]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page])

    respond_to do |format|
      format.html
      format.csv{ send_data @tasks.generate_csv, filename: "task-#{Time.zone.now.strftime('%Y%m%d%S')}" }
    end
  end

  def import
    current_user.tasks.import(params[:file])
    redirect_to root_path, notice: "タスクを追加しました。"
  end

  def show
  end

  def new
    @task = Task.new
  end

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  def create
    @task = current_user.tasks.new(task_params)

    if params[:back]
      render :new
      return
    end

    if @task.save
      SampleJob.perform_later
      redirect_to root_path, notice: "タスク【#{@task.name}】を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update!(task_params)
      redirect_to root_path, notice: "タスク【#{@task.name}】を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    head :no_content
  end

  private

    def set_task
      @task = current_user.tasks.find(params[:id])
    end

    def task_params
      params.
        require(:task).
          permit(
            :name,
            :description,
            :status_value,
            :image,
          )
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
- if task.errors.present?
  %ul#error_explanation
    - task.errors.full_messages.each do |message|
      %li= message

= form_with model: task, local: true do |form|

  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'

  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control'

  .form-group
    = form.label  :status_value
    = form.select :status_value, Task.status_values.keys, prompt: 'ステータスを選択してください', class: 'form-control'

  .form-group
    = form.label :image
    = form.file_field :image, class: 'form-control'

  .actions
    = form.submit nil, class: 'btn btn-outline-info'

app/views/tasks/confirm_new.html.haml
= form_with model: @task, local: true do |form|
  %table.table.table-hover
    %tr
      %th= Task.human_attribute_name(:name)
      %td= @task.name
      = form.hidden_field :name
    %tr
      %th= Task.human_attribute_name(:description)
      %td= simple_format(@task.description)
      = form.hidden_field :description
    %tr
      %th= Task.human_attribute_name(:status_value)
      %td= @task.status_value
      = form.hidden_field :status_value
  = form.submit '戻る', name: 'back', class: 'btn btn-outline-secondary mr-3'
  = form.submit '登録する', class: 'btn btn-outline-info'

app/views/tasks/edit.html.haml
%h1 タスク【 #{@task.name} 】を編集しています

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.haml
%h1 タスク一覧

= search_form_for @q, class: 'mb-5' do |form|
  .form-group.row
    = form.label :name_cont, Task.human_attribute_name(:name), class: 'col-sm-2 col-form-label'
    .col-sm-10
      = form.search_field :name_cont, class: 'form-control'
  .form-group.row
    = form.label :updated_at_gteq, Task.human_attribute_name(:updated_at), class: 'col-sm-2 col-form-label'
    .col-sm-10
      = form.search_field :updated_at_gteq, class: 'form-control'
  .form-group.row
    = form.submit class: 'btn btn-outline-info ml-3'
    = link_to 'クリア', tasks_path, class: 'btn btn-outline-secondary ml-3'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks

%table.table.table-hover
  %thead
    %tr
      -# %th= Task.human_attribute_name(:status_value)
      %th= sort_link(@q, :status_value, [:status_value, "updated_at desc"])
      %th= Task.human_attribute_name(:name)
      %th= Task.human_attribute_name(:updated_at)
      %th
  %tbody
    - @tasks.each do |task|
      %tr
        %td= t(task.status_value, scope: [:activerecord, :data, :task, :status_value])
        %td= link_to task.name, task_path(task)
        %td= l(task.updated_at, format: :long)
        %td
          = link_to '編集', edit_task_path(task), class: 'btn btn-sm btn-outline-info mr-3'
          = link_to '削除', task, method: :delete, remote: true, data: { confirm: "【#{task.name}】を削除してよろしいですか？"}, class: 'btn btn-sm btn-outline-secondary mr-3 delete'


= link_to 'タスクを作成する', new_task_path, class: 'btn btn-outline-info mr-3'

= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-outline-info'

= form_tag import_tasks_path, multipart: true, class: 'mt-5 mb-5' do
  = file_field_tag :file
  = submit_tag 'インポート', class: 'btn btn-outline-info'

app/views/tasks/new.html.haml
%h1 タスクの新規登録

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.haml
%h1 タスク【 #{@task.name} 】の詳細情報

%table.table.table-hover
  %tbody
    %tr
      %th= Task.human_attribute_name(:name)
      %td= @task.name
    %tr
      %th= Task.human_attribute_name(:description)
      %td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")
    %tr
      %th= Task.human_attribute_name(:status_value)
      %td= t(@task.status_value, scope: [:activerecord, :data, :task, :status_value])
    %tr
      %th= Task.human_attribute_name(:updated_at)
      %td= l(@task.updated_at, format: :long)
    %tr
      %th= Task.human_attribute_name(:image)
      %td= image_tag @task.image if @task.image.attached?

= link_to '編集', edit_task_path(@task), class: 'btn btn-sm btn-outline-info mr-3'
= link_to '削除', @task, method: :delete, data: { confirm: "【#{@task.name}】を削除してよろしいですか？"}, class: 'btn btn-sm btn-outline-secondary mr-3'