config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#create
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#               admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                           POST   /admin/users(.:format)                                                                   admin/users#create
#            new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#           edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                           PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                           PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                           DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#                      root GET    /                                                                                        tasks#index
#          confirm_new_task POST   /tasks/new/confirm(.:format)                                                             tasks#confirm_new
#              import_tasks POST   /tasks/import(.:format)                                                                  tasks#import
#                     tasks GET    /tasks(.:format)                                                                         tasks#index
#                           POST   /tasks(.:format)                                                                         tasks#create
#                  new_task GET    /tasks/new(.:format)                                                                     tasks#new
#                 edit_task GET    /tasks/:id/edit(.:format)                                                                tasks#edit
#                      task GET    /tasks/:id(.:format)                                                                     tasks#show
#                           PATCH  /tasks/:id(.:format)                                                                     tasks#update
#                           PUT    /tasks/:id(.:format)                                                                     tasks#update
#                           DELETE /tasks/:id(.:format)                                                                     tasks#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  get  '/login'   , to: 'sessions#new'
  post '/login'   , to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
    post :import, on: :collection
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  admin           :boolean          default(FALSE), not null
#  email           :string           not null
#  locale          :string           default("ja")
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  has_secure_password

  has_many :tasks

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:name)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザ【#{@user.name}】を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザ【#{@user.name}】を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザ【#{@user.name}】を削除しました。"
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :locale, :admin, :password, :password_confirmation)
    end

    def require_admin
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.haml
- if user.errors.present?
  %ul#error_explanation
    - user.errors.full_messages.each do |message|
      %li= message

= form_with model: [:admin, user], local: true do |form|

  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'

  .form-group
    = form.label :email
    = form.text_field :email, class: 'form-control'

  .form-group
    = form.label :locale, class: 'form-check-label' do
      .radio_buttons
        = form.radio_button :locale, 'en',  class: 'form-control'
        English
        = form.radio_button :locale, 'ja',  class: 'form-control'
        Japanese

  .form-check
    = form.label :admin, class: 'form-check-label' do
      = form.check_box :admin, class: 'form-control'
      admin

  .form-group
    = form.label :password
    = form.password_field :password, class: 'form-control'

  .form-group
    = form.label :password_confirmation
    = form.password_field :password_confirmation, class: 'form-control'

  .actions
    = form.submit nil, class: 'btn btn-outline-info'

app/views/admin/users/edit.html.haml
%h1 ユーザ【 #{@user.name} 】を編集しています

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.haml
%h1 ユーザ一覧

.mb-3
%table.table.table-hover
  %thead
    %tr
      %th= User.human_attribute_name(:name)
      %th= User.human_attribute_name(:email)
      %th= User.human_attribute_name(:locale)
      %th= User.human_attribute_name(:admin)
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.name, admin_user_path(user)
        %td= user.email
        %td= user.locale == 'ja' ? '日本語' : '英語'
        %td= user.admin? ? 'あり' : 'なし'
        %td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-sm btn-outline-info mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "【#{user.name}】を削除してよろしいですか？"}, class: 'btn btn-sm btn-outline-secondary mr-3'


= link_to 'ユーザを登録する', new_admin_user_path, class: 'btn btn-outline-info'

app/views/admin/users/new.html.haml
%h1 ユーザの新規登録

.nav.justify-content-end
  = link_to 'ユーザ一覧へ戻る', admin_users_path, class: "nav-link"

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.haml
%h1.mt-3 ユーザ【 #{@user.name} 】の詳細情報

.show_buttons
  = link_to '編集', edit_admin_user_path(@user), class: 'btn btn-sm btn-outline-info mr-3'
  = link_to '削除', [:admin, @user], method: :delete, data: { confirm: "【#{@user.name}】を削除してよろしいですか？"}, class: 'btn btn-sm btn-outline-secondary mr-3'
  = link_to 'ユーザ一覧へ戻る', admin_users_path, class: "btn btn-sm btn-outline-secondary"


%table.table.table-hover.mt-3.md-3
  %tbody
    %tr
      %th= User.human_attribute_name(:name)
      %td= @user.name
    %tr
      %th= User.human_attribute_name(:email)
      %td= @user.email
    %tr
      %th= User.human_attribute_name(:locale)
      %td= @user.locale == 'ja' ? '日本語' : '英語'
    %tr
      %th= User.human_attribute_name(:admin)
      %td= @user.admin? ? 'あり' : 'なし'

.users_tasks_table.mt-5.ml-5
  %h5 タスク一覧

  %table.table.table-hover
    %tbody
      %tr
        %th= Task.human_attribute_name(:name)
        %th= Task.human_attribute_name(:description)
        %th= Task.human_attribute_name(:created_at)
      - @user.tasks.each do |task|
        %tr
          %td= link_to task.name, task_path(task)
          %td= task.description
          %td= l(task.created_at, format: :long)